#ifndef HAL_ARDUINOMEGA_SERIAL_H
#define HAL_ARDUINOMEGA_SERIAL_H

#include <stdbool.h>

void ATMEGA2560_UART_INIT(void);
void ATMEGA2560_UART_PUTCHAR(char c);
char ATMEGA2560_UART_GETCHAR(void);
bool ATMEGA2560_UART_RXBUFFER_READY(void);

FILE uart_output = FDEV_SETUP_STREAM(ATMEGA2560_UART_PUTCHAR, NULL, _FDEV_SETUP_WRITE);
FILE uart_input = FDEV_SETUP_STREAM(NULL, ATMEGA2560_UART_GETCHAR, _FDEV_SETUP_READ);

#endif